Update build_test.yml #3

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -119,107 +119,107 @@ jobs:
                   name: "jmbde-macOS_swift_5_3_${{ matrix.config.os }}-${{ github.sha }}"
                   path: build/bin/${{ matrix.config.binary }}
 
-    iOS:
-        name: "Test Build iOS"
-        runs-on: macOS-latest
-        env:
-            DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
-        strategy:
-            matrix:
-                destination: ["OS=14.0,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
-        steps:
-            - uses: actions/checkout@v2
-              with:
-                  submodules: recursive
-                  fetch-depth: 0
-            - uses: actions/cache@v2.1.2
-              id: bundler-cache
-              with:
-                  path: vendor/bundle
-                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
-                  restore-keys: |
-                      ${{ runner.os }}-gems-
-            - name: Bundle setup
-              run: bundle config path vendor/bundle
-            - name: Bundle install
-              if: steps.bundler-cache.outputs.cache-hit != 'true'
-              run: bundle install --jobs 4 --retry 3
-            - name: Brew Upgrade
-              run: |
-                  brew update-reset
-                  brew bundle --no-upgrade
+    # iOS:
+    #     name: "Test Build iOS"
+    #     runs-on: macOS-latest
+    #     env:
+    #         DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
+    #     strategy:
+    #         matrix:
+    #             destination: ["OS=14.0,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
+    #     steps:
+    #         - uses: actions/checkout@v2
+    #           with:
+    #               submodules: recursive
+    #               fetch-depth: 0
+    #         - uses: actions/cache@v2.1.2
+    #           id: bundler-cache
+    #           with:
+    #               path: vendor/bundle
+    #               key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+    #               restore-keys: |
+    #                   ${{ runner.os }}-gems-
+    #         - name: Bundle setup
+    #           run: bundle config path vendor/bundle
+    #         - name: Bundle install
+    #           if: steps.bundler-cache.outputs.cache-hit != 'true'
+    #           run: bundle install --jobs 4 --retry 3
+    #         - name: Brew Upgrade
+    #           run: |
+    #               brew update-reset
+    #               brew bundle --no-upgrade
 
-            - name: Build_iOS
-              run: |
-                  pod install || pod install --repo-update
-                  set -o pipefail && xcodebuild -workspace "jmbde.xcworkspace" -scheme "jmbde iOS" -destination "${{ matrix.destination }}" clean test | xcpretty
+    #         - name: Build_iOS
+    #           run: |
+    #               pod install || pod install --repo-update
+    #               set -o pipefail && xcodebuild -workspace "jmbde.xcworkspace" -scheme "jmbde iOS" -destination "${{ matrix.destination }}" clean test | xcpretty
 
-    tvOS:
-        name: "Test tvOS"
-        runs-on: macOS-latest
-        env:
-            DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
-        strategy:
-            matrix:
-                destination: ["OS=14.0,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
-        steps:
-            - uses: actions/checkout@v2
-              with:
-                  submodules: recursive
-                  fetch-depth: 0
-            - uses: actions/cache@v2.1.2
-              id: bundler-cache
-              with:
-                  path: vendor/bundle
-                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
-                  restore-keys: |
-                      ${{ runner.os }}-gems-
-            - name: Bundle setup
-              run: bundle config path vendor/bundle
-            - name: Bundle install
-              if: steps.bundler-cache.outputs.cache-hit != 'true'
-              run: bundle install --jobs 4 --retry 3
-            - name: Brew Upgrade
-              run: |
-                  brew update-reset
-                  brew bundle --no-upgrade
+    # tvOS:
+    #     name: "Test tvOS"
+    #     runs-on: macOS-latest
+    #     env:
+    #         DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
+    #     strategy:
+    #         matrix:
+    #             destination: ["OS=14.0,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
+    #     steps:
+    #         - uses: actions/checkout@v2
+    #           with:
+    #               submodules: recursive
+    #               fetch-depth: 0
+    #         - uses: actions/cache@v2.1.2
+    #           id: bundler-cache
+    #           with:
+    #               path: vendor/bundle
+    #               key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+    #               restore-keys: |
+    #                   ${{ runner.os }}-gems-
+    #         - name: Bundle setup
+    #           run: bundle config path vendor/bundle
+    #         - name: Bundle install
+    #           if: steps.bundler-cache.outputs.cache-hit != 'true'
+    #           run: bundle install --jobs 4 --retry 3
+    #         - name: Brew Upgrade
+    #           run: |
+    #               brew update-reset
+    #               brew bundle --no-upgrade
 
-            - name: tvOS - ${{ matrix.destination }}
-              run: |
-                  pod install || pod install --repo-update
-                  set -o pipefail && xcodebuild -workspace "jmbde.xcworkspace" -scheme "jmbde tvOS" -destination "${{ matrix.destination }}" clean test | xcpretty
+    #         - name: tvOS - ${{ matrix.destination }}
+    #           run: |
+    #               pod install || pod install --repo-update
+    #               set -o pipefail && xcodebuild -workspace "jmbde.xcworkspace" -scheme "jmbde tvOS" -destination "${{ matrix.destination }}" clean test | xcpretty
 
-    watchOS:
-        name: "Test watchOS"
-        runs-on: macOS-latest
-        env:
-            DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
-        strategy:
-            matrix:
-                destination: ["OS=7.0,name=Apple Watch Series 5 - 44mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
-        steps:
-            - uses: actions/checkout@v2
-              with:
-                  submodules: recursive
-                  fetch-depth: 0
-            - uses: actions/cache@v2.1.2
-              id: bundler-cache
-              with:
-                  path: vendor/bundle
-                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
-                  restore-keys: |
-                      ${{ runner.os }}-gems-
-            - name: Bundle setup
-              run: bundle config path vendor/bundle
-            - name: Bundle install
-              if: steps.bundler-cache.outputs.cache-hit != 'true'
-              run: bundle install --jobs 4 --retry 3
-            - name: Brew Upgrade
-              run: |
-                  brew update-reset
-                  brew bundle --no-upgrade
+    # watchOS:
+    #     name: "Test watchOS"
+    #     runs-on: macOS-latest
+    #     env:
+    #         DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
+    #     strategy:
+    #         matrix:
+    #             destination: ["OS=7.0,name=Apple Watch Series 5 - 44mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
+    #     steps:
+    #         - uses: actions/checkout@v2
+    #           with:
+    #               submodules: recursive
+    #               fetch-depth: 0
+    #         - uses: actions/cache@v2.1.2
+    #           id: bundler-cache
+    #           with:
+    #               path: vendor/bundle
+    #               key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+    #               restore-keys: |
+    #                   ${{ runner.os }}-gems-
+    #         - name: Bundle setup
+    #           run: bundle config path vendor/bundle
+    #         - name: Bundle install
+    #           if: steps.bundler-cache.outputs.cache-hit != 'true'
+    #           run: bundle install --jobs 4 --retry 3
+    #         - name: Brew Upgrade
+    #           run: |
+    #               brew update-reset
+    #               brew bundle --no-upgrade
 
-            - name: tvOS - ${{ matrix.destination }}
-              run: |
-                  pod install || pod install --repo-update
-                  set -o pipefail && xcodebuild -workspace "jmbde.xcworkspace" -scheme "jmbde watchOS" -destination "${{ matrix.destination }}" clean test | xcpretty
+    #         - name: tvOS - ${{ matrix.destination }}
+    #           run: |
+    #               pod install || pod install --repo-update
+    #               set -o pipefail && xcodebuild -workspace "jmbde.xcworkspace" -scheme "jmbde watchOS" -destination "${{ matrix.destination }}" clean test | xcpretty
